image: docker:stable

stages:
  - build web-scraper image
  - build rest-api image

docker build:
  stage: build web-scraper image
  script:
    - docker info
    - docker build -t web-scraper ./web-scraper

  stage: build rest-api image
  script:
    - docker build -t rest-api ./api
