version: '3.2'

services:
  database:
    image: postgres:9.6
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: teonite321
      POSTGRES_USER: teonite

  rest-api:
    restart: always
    build: ./api
    container_name: rest-api
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_NAME: teonite
      DB_HOST: postgres
      DB_USER: teonite
      DB_PASSWORD: teonite321
      DB_PORT: 5432
      ALLOWED_HOST: '*'
      DEBUG: 'False'
      SECRET_KEY: not_so_secret_key

  web-scraper:
    restart: on-failure
    build: ./web-scraper
    container_name: web-scraper
    depends_on:
      - database
      - rest-api
