# Generated by Django 2.1.7 on 2019-04-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ('author_id',),
            },
        ),
        migrations.CreateModel(
            name='TotalWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('word_count', models.IntegerField()),
            ],
            options={
                'db_table': 'total_words',
                'ordering': ('-word_count',),
            },
        ),
        migrations.CreateModel(
            name='WordsPerAuthor',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('word_count', models.IntegerField()),
            ],
            options={
                'db_table': 'personal_words',
                'ordering': ('-word_count',),
            },
        ),
    ]
