# Generated by Django 2.1.7 on 2019-04-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordsperauthor',
            unique_together={('word', 'author_id')},
        ),
    ]
