# Generated by Django 2.1.7 on 2019-04-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190415_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordsperauthor',
            unique_together=set(),
        ),
    ]
